// src/svelte/Player.svelte
<!--
  Svelte 5 adapter (runes syntax — requires svelte >=5.0.0, no Svelte 3/4
  legacy-syntax support). Same thin-wrapper pattern as src/react/Player.js
  and src/vue/Player.js: compute resolveSource(url) at render time, render
  an SSR-visible poster+link+JSON-LD fallback around an always-empty inner
  mount div, call createPlayer(innerDiv, options) once mounted client-side.

  Two-node split — same reasoning as React/Vue, ported to Svelte's own
  mechanism: Svelte's compiler generates DOM-anchor bookkeeping for {#if}
  blocks against nodes it created. If the mount target (bind:this)
  were inside a block Svelte also manages, createPlayer's innerHTML/append()
  calls would remove anchors Svelte still expects there, corrupting the DOM
  on the next `mounted` flip. Keeping the mount div as an always-rendered
  sibling — never inside an {#if} — sidesteps that entirely, same as
  React's/Vue's separate inner div.

  onEvent is a plain callback prop, not a dispatched CustomEvent — Svelte 5
  deprecated createEventDispatcher in favor of exactly this pattern, so this
  needs less glue than Vue's `emits: ['event']` wrapper and matches
  PlayerOptions.onEvent's signature directly.
-->
<script>
  import { onDestroy, onMount } from 'svelte';
  import { createPlayer } from '../core/controller.js';
  import { resolveSource } from '../resolvers/index.js';
  import { posterUrlFor } from '../core/lazy.js';
  import { buildVideoObjectJsonLd, stringifyForScriptTag } from '../core/seo.js';

  let {
    url,
    controls = true,
    light = false,
    poster,
    autoplay = false,
    muted = false,
    loop = false,
    playbackRates,
    volume,
    volumeKey,
    videoSize = 'contain',
    centerPlayButton = false,
    loadingSpinner = true,
    theme,
    shield = true,
    seo,
    onEvent,
    class: className,
    style,
  } = $props();

  let containerEl = $state(null);
  // Tracks whether createPlayer has actually taken over the inner div.
  // Starts false so server and initial-client render agree (no hydration
  // mismatch); the SEO poster fallback below is only shown until then —
  // both it and the real player are absolutely positioned over the same
  // box, so leaving the fallback mounted forever would permanently cover
  // the real player once it's up.
  let mounted = $state(false);
  let player = null;

  const resolved = $derived(resolveSource(url));
  const fallbackPoster = $derived(poster ?? (resolved ? posterUrlFor(resolved) : undefined));
  const jsonLd = $derived(seo ? buildVideoObjectJsonLd(resolved, url, seo) : null);
  const jsonLdScript = $derived(jsonLd ? `<script type="application/ld+json">${stringifyForScriptTag(jsonLd)}<\/script>` : '');

  function mount() {
    player?.destroy();
    mounted = false;
    if (!containerEl) return;

    player = createPlayer(containerEl, {
      url,
      controls,
      light,
      poster,
      autoplay,
      muted,
      loop,
      playbackRates,
      volume,
      volumeKey,
      videoSize,
      centerPlayButton,
      loadingSpinner,
      theme,
      shield,
      seo,
      onEvent,
    });
    mounted = true;
  }

  // Client-only — onMount never runs during SSR, matching React's
  // useEffect / Vue's onMounted. Re-mounts only when `url` changes, matching
  // the vanilla API's one-shot createPlayer(container, options) contract and
  // the React/Vue adapters' existing behavior.
  onMount(mount);
  let previousUrl = url;
  $effect(() => {
    if (url !== previousUrl) {
      previousUrl = url;
      mount();
    }
  });
  onDestroy(() => player?.destroy());
</script>

<div class={className} style="position: relative; width: 100%; aspect-ratio: 16 / 9; {style ?? ''}">
  <div bind:this={containerEl} style="position: absolute; inset: 0;"></div>
  {#if !mounted && fallbackPoster}
    <a href={url} rel="noopener" style="position: absolute; inset: 0; display: block;">
      <img
        src={fallbackPoster}
        alt={seo?.name ?? 'Video thumbnail'}
        loading="lazy"
        style="width: 100%; height: 100%; object-fit: cover;"
      />
    </a>
  {/if}
  {#if jsonLd}
    {@html jsonLdScript}
  {/if}
</div>

// src/react/Player.js
// React adapter. Written with createElement (not JSX) so this file needs no
// build step / JSX transform of its own — consistent with the zero-tooling
// posture of the rest of the package. Mounts only in useEffect (client-side).
//
// SEO note: the outer div below carries a real, server-renderable fallback
// (poster link + optional JSON-LD) as its own React-owned children, while
// the actual mount target passed to createPlayer is a separate, always-empty
// *inner* div. This split matters: createPlayer mutates its container with
// plain DOM calls (append/innerHTML), and if that container were the same
// node React renders children into, the next React re-render would try to
// reconcile its virtual children against a subtree React no longer
// recognizes (createPlayer already replaced it) — React throws trying to
// remove/update nodes it doesn't own. Keeping createPlayer's target as a
// leaf div with no React children sidesteps that entirely.
import { createElement, useEffect, useMemo, useRef, useState } from 'react';
import { createPlayer } from '../core/controller.js';
import { resolveSource } from '../resolvers/index.js';
import { posterUrlFor } from '../core/lazy.js';
import { buildVideoObjectJsonLd, stringifyForScriptTag } from '../core/seo.js';

const PLAYER_OPTION_KEYS = [
  'url',
  'controls',
  'light',
  'poster',
  'autoplay',
  'muted',
  'loop',
  'playbackRates',
  'volume',
  'volumeKey',
  'videoSize',
  'centerPlayButton',
  'theme',
  'shield',
  'onEvent',
];

/**
 * @typedef {import('../core/types.js').PlayerOptions & {
 *   className?: string,
 *   style?: import('react').CSSProperties,
 * }} PlayerProps
 */

/**
 * @param {PlayerProps} props
 * @returns {import('react').ReactElement}
 */
export function Player(props) {
  const containerRef = useRef(null);
  const playerRef = useRef(null);
  // Tracks whether createPlayer has actually taken over the inner div.
  // Starts false so server and initial-client render agree (no hydration
  // mismatch); the SEO poster fallback below is only shown until then —
  // both it and the real player are absolutely positioned over the same
  // box, so leaving the fallback mounted forever would permanently cover
  // the real player once it's up.
  const [mounted, setMounted] = useState(false);

  const resolved = useMemo(() => resolveSource(props.url), [props.url]);
  const fallbackPoster = props.poster ?? (resolved ? posterUrlFor(resolved) : undefined);
  const jsonLd = props.seo ? buildVideoObjectJsonLd(resolved, props.url, props.seo) : null;

  useEffect(() => {
    if (!containerRef.current) return undefined;

    const options = {};
    for (const key of PLAYER_OPTION_KEYS) {
      if (props[key] !== undefined) options[key] = props[key];
    }

    playerRef.current = createPlayer(containerRef.current, options);
    setMounted(true);
    return () => playerRef.current?.destroy();
    // Re-mounts only when the source URL changes — every other option is
    // read fresh on that same mount, matching the vanilla API's one-shot
    // createPlayer(container, options) contract (plan.md §4.1).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.url]);

  return createElement(
    'div',
    {
      className: props.className,
      style: { position: 'relative', width: '100%', aspectRatio: '16 / 9', ...props.style },
    },
    createElement('div', { ref: containerRef, style: { position: 'absolute', inset: 0 } }),
    !mounted &&
      fallbackPoster &&
      createElement(
        'a',
        {
          key: 'seo-fallback',
          href: props.url,
          rel: 'noopener',
          style: { position: 'absolute', inset: 0, display: 'block' },
        },
        createElement('img', {
          src: fallbackPoster,
          alt: props.seo?.name ?? 'Video thumbnail',
          loading: 'lazy',
          style: { width: '100%', height: '100%', objectFit: 'cover' },
        }),
      ),
    jsonLd &&
      createElement('script', {
        key: 'seo-jsonld',
        type: 'application/ld+json',
        dangerouslySetInnerHTML: { __html: stringifyForScriptTag(jsonLd) },
      }),
  );
}
